version: '3'
services:
  shipping-service:
    build: .
    ports:
     - "7074:7074"
    environment:
     - RABBITMQ_SERVICE_HOST=rabbitmq
     - SC_HOST=servicecenter
    links:
      - servicecenter:servicecenter
      - rabbitmq:rabbitmq
  rabbitmq:
    image: rabbitmq:3
    ports:
     - "5672:5672"
  servicecenter:
    image: servicecomb/service-center:latest
    ports:
     - "30100:30100"
